name: 'Library Release Action'
description: It is used to bump current library's version and publish a new package and release tag.
author: 'tronku'
branding:
  icon: 'box'
  color: 'yellow'

inputs:
  github_token:
    description: 'GitHub token to access your repo'
    required: true

  default_branch:
    description: 'Default branch of the repo'
    required: false
    default: 'development'

  main_branch:
    description: 'Main branch of the repo for release'
    required: false
    default: 'master'

  should_sync:
    description: 'Should sync default and main branch (for release only)'
    required: false
    default: 'false'

  auto_delete:
    description: 'Should delete old packages'
    required: false
    default: 'false'
    
  delete_version_count: 
    description: 'Number of versions to be deleted'
    required: false
    default: '10'

  packages_count:
    description: 'Number of packages in the repo'
    required: false
    default: '1'  
    
  package_file_path:
    description: 'Path of package.properties file'
    required: false
    default: 'package.properties'  

  version_file_path:
    description: 'Path of version.properties file'
    required: false
    default: 'version.properties'
  
  release_branch_prefix:
    description: 'Prefix of the version bump release branch'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.default_branch }}
    - ${{ inputs.main_branch }}    
    - ${{ inputs.version_file_path }}
    - ${{ inputs.should_sync }}
    - ${{ inputs.auto_delete }}
    - ${{ inputs.delete_version_count }}
    - ${{ inputs.packages_count }}
    - ${{ inputs.package_file_path }}
    - ${{ inputs.release_branch_prefix }}
